[package]
name = "libwiredtiger"
edition = "2021"
authors = ["Tyler Brock", "Mike O'Brien"]
description = "Native bindings for WiredTiger"
repository = "https://github.com/TylerBrock/wiredtiger-rust"
keywords = [ "bindings", "ffi", "wiredtiger" ]

[build-dependencies]
bindgen = "0.70.1"
